global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using FluentAssertions;
global using FluentAssertions.Execution;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using NUnit.Framework;
global using NUnit.Framework.Interfaces;
global using NUnit.Framework.Internal;
global using NUnit.Framework.Internal.Commands;
global using TestHarness.UITest.Ext.Navigation;
global using TestHarness.UITest.Extensions;
global using TestHarness.UITest.TestFramework;
global using Uno.UITest;
global using Uno.UITest.Helpers;
global using Uno.UITest.Helpers.Queries;
global using Uno.UITests.Helpers;
global using static System.Math;
global using Assert = Microsoft.VisualStudio.TestTools.UnitTesting.Assert;
global using IgnoreAttribute = NUnit.Framework.IgnoreAttribute;

