using TestHarness.Ext.Http.KiotaBuildGen.BuildGenClient;
using Uno.Extensions.Http.Kiota;
using Uno.Extensions.Http;

namespace TestHarness.Ext.Http.KiotaBuildGen;

/// <summary>
/// Host initialization for the Kiota MSBuild task (KiotaOpenApiReference)
/// build-time generation test scenario.
/// <para>
/// The <c>BuildGenPetClient</c> type is generated by the MSBuild task from
/// the <c>petstore-buildgen.json</c> OpenAPI spec declared as a
/// <c>&lt;KiotaOpenApiReference&gt;</c> in the project file.
/// </para>
/// </summary>
public class KiotaBuildGenHostInit : BaseHostInitialization
{
	protected override string[] ConfigurationFiles =>
		["TestHarness.Ext.Http.KiotaBuildGen.appsettings.kiotabuildgen.json"];

	protected override IHostBuilder Custom(IHostBuilder builder) =>
		builder
			.UseHttp((context, services) =>
				services.AddKiotaClient<BuildGenPetClient>(
					context,
					options: new EndpointOptions { Url = "https://localhost:5099" })
			)
			.ConfigureServices((context, services) =>
			{
				services.AddTransient<KiotaBuildGenHomeViewModel>();
			});

	protected override void RegisterRoutes(IViewRegistry views, IRouteRegistry routes)
	{
		views.Register(
			new ViewMap<KiotaBuildGenMainPage>(),
			new ViewMap<KiotaBuildGenHomePage, KiotaBuildGenHomeViewModel>()
		);

		routes.Register(
			new RouteMap("", View: views.FindByView<KiotaBuildGenMainPage>()),
			new RouteMap("Home", View: views.FindByViewModel<KiotaBuildGenHomeViewModel>())
		);
	}
}
