// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Task category — tests enum with dashed values</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Category
    {
        [EnumMember(Value = "bug-fix")]
        #pragma warning disable CS1591
        BugFix,
        #pragma warning restore CS1591
        [EnumMember(Value = "feature-request")]
        #pragma warning disable CS1591
        FeatureRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "documentation")]
        #pragma warning disable CS1591
        Documentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "tech-debt")]
        #pragma warning disable CS1591
        TechDebt,
        #pragma warning restore CS1591
        [EnumMember(Value = "security-patch")]
        #pragma warning disable CS1591
        SecurityPatch,
        #pragma warning restore CS1591
    }
}
