// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Label for categorization — used in array context</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Label
    {
        [EnumMember(Value = "frontend")]
        #pragma warning disable CS1591
        Frontend,
        #pragma warning restore CS1591
        [EnumMember(Value = "backend")]
        #pragma warning disable CS1591
        Backend,
        #pragma warning restore CS1591
        [EnumMember(Value = "infrastructure")]
        #pragma warning disable CS1591
        Infrastructure,
        #pragma warning restore CS1591
        [EnumMember(Value = "database")]
        #pragma warning disable CS1591
        Database,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "ui-ux")]
        #pragma warning disable CS1591
        UiUx,
        #pragma warning restore CS1591
    }
}
