// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Types of notifications — used in array context</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NotificationType
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "push")]
        #pragma warning disable CS1591
        Push,
        #pragma warning restore CS1591
        [EnumMember(Value = "in-app")]
        #pragma warning disable CS1591
        InApp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
    }
}
