// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Permission flags — tests flags enum pattern (used in array context as bit flags)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Permission
    {
        [EnumMember(Value = "read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
        [EnumMember(Value = "write")]
        #pragma warning disable CS1591
        Write,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "export")]
        #pragma warning disable CS1591
        Export,
        #pragma warning restore CS1591
    }
}
