// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Fields available for sorting</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SortField
    {
        [EnumMember(Value = "createdAt")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "dueDate")]
        #pragma warning disable CS1591
        DueDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
    }
}
