// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Enums.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assigneeId property</summary>
        public Guid? AssigneeId { get; set; }
        /// <summary>Task category — tests enum with dashed values</summary>
        public global::Enums.Client.Models.Category? Category { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The dueDate property</summary>
        public Date? DueDate { get; set; }
        /// <summary>The estimatedHours property</summary>
        public float? EstimatedHours { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>Labels/tags applied to this task — tests array of enums</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Enums.Client.Models.Label?>? Labels { get; set; }
#nullable restore
#else
        public List<global::Enums.Client.Models.Label?> Labels { get; set; }
#endif
        /// <summary>Permission flags — tests flags enum pattern (used in array context as bit flags)</summary>
        public global::Enums.Client.Models.Permission? Permissions { get; set; }
        /// <summary>Priority level — basic string enum</summary>
        public global::Enums.Client.Models.Priority? Priority { get; set; }
        /// <summary>Status of a task — basic string enum</summary>
        public global::Enums.Client.Models.TaskStatus? Status { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Visibility level</summary>
        public global::Enums.Client.Models.Visibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Enums.Client.Models.TaskItem"/> and sets the default values.
        /// </summary>
        public TaskItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Enums.Client.Models.TaskItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Enums.Client.Models.TaskItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Enums.Client.Models.TaskItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigneeId", n => { AssigneeId = n.GetGuidValue(); } },
                { "category", n => { Category = n.GetEnumValue<global::Enums.Client.Models.Category>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "dueDate", n => { DueDate = n.GetDateValue(); } },
                { "estimatedHours", n => { EstimatedHours = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfEnumValues<global::Enums.Client.Models.Label>()?.AsList(); } },
                { "permissions", n => { Permissions = n.GetEnumValue<global::Enums.Client.Models.Permission>(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::Enums.Client.Models.Priority>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Enums.Client.Models.TaskStatus>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::Enums.Client.Models.Visibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("assigneeId", AssigneeId);
            writer.WriteEnumValue<global::Enums.Client.Models.Category>("category", Category);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("dueDate", DueDate);
            writer.WriteFloatValue("estimatedHours", EstimatedHours);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfEnumValues<global::Enums.Client.Models.Label>("labels", Labels);
            writer.WriteEnumValue<global::Enums.Client.Models.Permission>("permissions", Permissions);
            writer.WriteEnumValue<global::Enums.Client.Models.Priority>("priority", Priority);
            writer.WriteEnumValue<global::Enums.Client.Models.TaskStatus>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Enums.Client.Models.Visibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
