// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Status of a task — basic string enum</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskStatus
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "in-progress")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "review")]
        #pragma warning disable CS1591
        Review,
        #pragma warning restore CS1591
        [EnumMember(Value = "done")]
        #pragma warning disable CS1591
        Done,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
