// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>UI theme preference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Theme
    {
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
        [EnumMember(Value = "dark")]
        #pragma warning disable CS1591
        Dark,
        #pragma warning restore CS1591
        [EnumMember(Value = "system-default")]
        #pragma warning disable CS1591
        SystemDefault,
        #pragma warning restore CS1591
        [EnumMember(Value = "high-contrast")]
        #pragma warning disable CS1591
        HighContrast,
        #pragma warning restore CS1591
    }
}
