// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>User role — simple string enum</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserRole
    {
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "super-admin")]
        #pragma warning disable CS1591
        SuperAdmin,
        #pragma warning restore CS1591
    }
}
