// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Enums.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class User : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Notification types the user wants to receive — tests array of enums</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Enums.Client.Models.NotificationType?>? NotificationPreferences { get; set; }
#nullable restore
#else
        public List<global::Enums.Client.Models.NotificationType?> NotificationPreferences { get; set; }
#endif
        /// <summary>Permission flags — tests flags enum pattern (used in array context as bit flags)</summary>
        public global::Enums.Client.Models.Permission? Permissions { get; set; }
        /// <summary>UI theme preference</summary>
        public global::Enums.Client.Models.Theme? PreferredTheme { get; set; }
        /// <summary>User role — simple string enum</summary>
        public global::Enums.Client.Models.UserRole? Role { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Enums.Client.Models.User"/> and sets the default values.
        /// </summary>
        public User()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Enums.Client.Models.User"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Enums.Client.Models.User CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Enums.Client.Models.User();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notificationPreferences", n => { NotificationPreferences = n.GetCollectionOfEnumValues<global::Enums.Client.Models.NotificationType>()?.AsList(); } },
                { "permissions", n => { Permissions = n.GetEnumValue<global::Enums.Client.Models.Permission>(); } },
                { "preferredTheme", n => { PreferredTheme = n.GetEnumValue<global::Enums.Client.Models.Theme>(); } },
                { "role", n => { Role = n.GetEnumValue<global::Enums.Client.Models.UserRole>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfEnumValues<global::Enums.Client.Models.NotificationType>("notificationPreferences", NotificationPreferences);
            writer.WriteEnumValue<global::Enums.Client.Models.Permission>("permissions", Permissions);
            writer.WriteEnumValue<global::Enums.Client.Models.Theme>("preferredTheme", PreferredTheme);
            writer.WriteEnumValue<global::Enums.Client.Models.UserRole>("role", Role);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
