// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Enums.Client.Models
{
    /// <summary>Visibility level</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Visibility
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
        [EnumMember(Value = "team-only")]
        #pragma warning disable CS1591
        TeamOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
    }
}
