name: Build Mobile
description: ""

inputs:
  package-id:
    description: 'Compiled Package ID'
    required: true
    default: 'release_Mobile'
  project-to-build:
    description: 'Relative path to .csproj file'
    required: true
    default: ''
  project-folder:
    description: 'csproj folder'
    required: true
    default: ''  
  artifact-retention-policy: 
    description: 'Number of days to keep the build artifacts'
    required: false
    default: '90'
  target-framework: 
    description: 'Target framework (net7.0-android, net7.0-ios, net7.0-maccatalyst)'
    required: true
    default: 'net7.0-android'
  publish-artifacts: 
     description: "If true, compilation artifacts will be published and put under Job Summary section"
     required: false
     default: 'true'     
        
runs:
  using: "composite"
  steps:
    - name: Verify required parameters
      shell: pwsh
      run: |
            $errors = ''
            if ('' -eq '${{ inputs.project-to-build }}') { $errors = $errors + '[project-to-build] is not valid.' + "`r`n"  }
            if ('' -eq '${{ inputs.target-framework }}') { $errors = $errors + '[target-framework] is not valid' + "`r`n"  }
            
            if (-not ([string]::IsNullOrEmpty($errors))){
                $errors
                throw "Some required parameters are missing"
            }

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        configFilePath: ./.github/workflows/config/gitversion.yml

    # Create the app package by building and packaging the project
    - name: Build and create package
      shell: pwsh
      run: |
        Write-Host  ""
        Write-Host "Building ${{ inputs.package-id }}"
        dotnet build  -c Release -p:TargetFramework=${{ inputs.target-framework }}  -o ${{ inputs.project-folder }}\bin\Release ${{ inputs.project-to-build }}

        $finalPackageFolder = "artifacts"
        Write-Host "Creating package folder: $finalPackageFolder"
        New-Item -ItemType Directory -Force -Path $finalPackageFolder

        if ('true' -eq '${{ inputs.publish-artifacts }}') {
          Copy-Item -Path '${{ inputs.project-folder }}\bin\Release\*' -Destination "artifacts" -recurse -Force  
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.package-id }}_${{ steps.gitversion.outputs.assemblySemVer }}" 
        path: artifacts
        retention-days: ${{ inputs.artifact-retention-policy }}