// <auto-generated/>
#pragma warning disable CS0618
using ErrorResponses.Client.Models;
using ErrorResponses.Client.Resources.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ErrorResponses.Client.Resources
{
    /// <summary>
    /// Builds and executes requests for operations under \resources
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResourcesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ErrorResponses.Client.resources.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder"/></returns>
        public global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("resourceId", position);
                return new global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ErrorResponses.Client.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources{?limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ErrorResponses.Client.Resources.ResourcesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResourcesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources{?limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns resources with standard error responses.
        /// </summary>
        /// <returns>A List&lt;global::ErrorResponses.Client.Models.Resource&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ErrorResponses.Client.Models.ValidationError">When receiving a 400 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.AuthenticationError">When receiving a 401 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.AuthorizationError">When receiving a 403 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.RateLimitError">When receiving a 429 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.ServiceUnavailableError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ErrorResponses.Client.Models.Resource>?> GetAsync(Action<RequestConfiguration<global::ErrorResponses.Client.Resources.ResourcesRequestBuilder.ResourcesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ErrorResponses.Client.Models.Resource>> GetAsync(Action<RequestConfiguration<global::ErrorResponses.Client.Resources.ResourcesRequestBuilder.ResourcesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ErrorResponses.Client.Models.ValidationError.CreateFromDiscriminatorValue },
                { "401", global::ErrorResponses.Client.Models.AuthenticationError.CreateFromDiscriminatorValue },
                { "403", global::ErrorResponses.Client.Models.AuthorizationError.CreateFromDiscriminatorValue },
                { "429", global::ErrorResponses.Client.Models.RateLimitError.CreateFromDiscriminatorValue },
                { "500", global::ErrorResponses.Client.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::ErrorResponses.Client.Models.ServiceUnavailableError.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ErrorResponses.Client.Models.Resource>(requestInfo, global::ErrorResponses.Client.Models.Resource.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Create a resource
        /// </summary>
        /// <returns>A <see cref="global::ErrorResponses.Client.Models.Resource"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ErrorResponses.Client.Models.GeneralError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ErrorResponses.Client.Models.Resource?> PostAsync(global::ErrorResponses.Client.Models.CreateResourceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ErrorResponses.Client.Models.Resource> PostAsync(global::ErrorResponses.Client.Models.CreateResourceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::ErrorResponses.Client.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ErrorResponses.Client.Models.Resource>(requestInfo, global::ErrorResponses.Client.Models.Resource.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns resources with standard error responses.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ErrorResponses.Client.Resources.ResourcesRequestBuilder.ResourcesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ErrorResponses.Client.Resources.ResourcesRequestBuilder.ResourcesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a resource
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ErrorResponses.Client.Models.CreateResourceRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ErrorResponses.Client.Models.CreateResourceRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ErrorResponses.Client.Resources.ResourcesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ErrorResponses.Client.Resources.ResourcesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ErrorResponses.Client.Resources.ResourcesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns resources with standard error responses.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ResourcesRequestBuilderGetQueryParameters 
        {
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
    }
}
#pragma warning restore CS0618
