<Project Sdk="Uno.Sdk.Private">
	<Import Project="..\..\..\src\tfms-ui-winui.props" />

	<PropertyGroup>

		<OutputType>Exe</OutputType>
		<UnoSingleProject>true</UnoSingleProject>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- Display name -->
		<ApplicationTitle>Playground</ApplicationTitle>
		<!-- App Identifier -->
		<ApplicationId>com.companyname.Playground</ApplicationId>
		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		<!--
			If you encounter this error message:

				error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll.
				Please update to a newer .NET SDK in order to reference this assembly.

			This means that the two packages below must be aligned with the "build" version number of
			the "Microsoft.Windows.SDK.BuildTools" package above, and the "revision" version number
			must be the highest found in https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref.
		-->
		<!-- <WindowsSdkPackageVersion>10.0.22621.28</WindowsSdkPackageVersion> -->

		<!--
			UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
			https://aka.platform.uno/singleproject-features
		-->
		<UnoFeatures>
			Material;
			SkiaRenderer;
			Toolkit;
			Mvvm;
		</UnoFeatures>
		
		<!--
			The Uno.Sdk.Private is pulling Microsoft.WindowsAppSDK v1.6, while the Uno.Sdk used to build packages is using v1.7
			This causes the buidl to fail as we 2 different references to the WebView2Loader.dll.
			By setting this property, we force the Uno.Sdk[.Private] to use the same version as the one used when building the extension packages.
		-->
		<WinAppSdkVersion>1.7.250909003</WinAppSdkVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.development.json" />
		<None Remove="appsettings.json" />
		<None Remove="data.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.development.json" />
		<EmbeddedResource Include="appsettings.json" />
		<Content Include="data.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Uno.Extensions.Configuration" />
		<PackageReference Include="Uno.Extensions.Core" />
		<PackageReference Include="Uno.Extensions.Hosting.WinUI" />
		<PackageReference Include="Uno.Extensions.Hosting" />
		<PackageReference Include="Uno.Extensions.Http.Refit" />
		<PackageReference Include="Uno.Extensions.Http.WinUI" />
		<PackageReference Include="Uno.Extensions.Http" />
		<PackageReference Include="Uno.Extensions.Localization.WinUI" />
		<PackageReference Include="Uno.Extensions.Logging.WinUI" />
		<PackageReference Include="Uno.Extensions.Navigation.Toolkit.WinUI" />
		<PackageReference Include="Uno.Extensions.Navigation.WinUI" />
		<PackageReference Include="Uno.Extensions.Navigation" />
		<PackageReference Include="Uno.Extensions.Reactive.WinUI" />
		<PackageReference Include="Uno.Extensions.Reactive" />
		<PackageReference Include="Uno.Extensions.Serialization.Http" />
		<PackageReference Include="Uno.Extensions.Serialization.Refit" />
		<PackageReference Include="Uno.Extensions.Serialization" />
		<PackageReference Include="Uno.Extensions.Storage.WinUI" />
		<PackageReference Include="Uno.Extensions.Storage" />
		<PackageReference Include="Uno.Extensions.Validation.Fluent" />
		<PackageReference Include="Uno.Extensions.Validation" />
	</ItemGroup>


</Project>
