// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PetStore.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePetRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The birthDate property</summary>
        public Date? BirthDate { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PetStore.Client.Models.Category? Category { get; set; }
#nullable restore
#else
        public global::PetStore.Client.Models.Category Category { get; set; }
#endif
        /// <summary>Name of the pet</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The photoUrls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PhotoUrls { get; set; }
#nullable restore
#else
        public List<string> PhotoUrls { get; set; }
#endif
        /// <summary>Status of a pet in the store</summary>
        public global::PetStore.Client.Models.PetStatus? Status { get; set; }
        /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PetStore.Client.Models.Tag>? Tags { get; set; }
#nullable restore
#else
        public List<global::PetStore.Client.Models.Tag> Tags { get; set; }
#endif
        /// <summary>The weight property</summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PetStore.Client.Models.CreatePetRequest"/> and sets the default values.
        /// </summary>
        public CreatePetRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PetStore.Client.Models.CreatePetRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PetStore.Client.Models.CreatePetRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PetStore.Client.Models.CreatePetRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "birthDate", n => { BirthDate = n.GetDateValue(); } },
                { "category", n => { Category = n.GetObjectValue<global::PetStore.Client.Models.Category>(global::PetStore.Client.Models.Category.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "photoUrls", n => { PhotoUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::PetStore.Client.Models.PetStatus>(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::PetStore.Client.Models.Tag>(global::PetStore.Client.Models.Tag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("birthDate", BirthDate);
            writer.WriteObjectValue<global::PetStore.Client.Models.Category>("category", Category);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("photoUrls", PhotoUrls);
            writer.WriteEnumValue<global::PetStore.Client.Models.PetStatus>("status", Status);
            writer.WriteStringValue("tag", Tag);
            writer.WriteCollectionOfObjectValues<global::PetStore.Client.Models.Tag>("tags", Tags);
            writer.WriteDoubleValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
