// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PetStore.Client.Models
{
    /// <summary>Status of a pet in the store</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PetStatus
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "adopted")]
        #pragma warning disable CS1591
        Adopted,
        #pragma warning restore CS1591
        [EnumMember(Value = "fostered")]
        #pragma warning disable CS1591
        Fostered,
        #pragma warning restore CS1591
    }
}
