<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ImplicitUsings>false</ImplicitUsings>

		<!-- Ships as the analyzer/tool of the Mocking package -->
		<ToolOfPackage>Uno.Extensions.Reactive.Mocking</ToolOfPackage>

		<NoWarn>$(NoWarn);RS2008</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Uno.Roslyn" PrivateAssets="All" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\Uno.Extensions.Core\_Compat\**\*.cs" Link="_Compat\%(RecursiveDir)%(Filename)%(Extension)" />
		<Compile Include="..\Uno.Extensions.Core.Generators\Common\**\*.cs" Link="Common\%(RecursiveDir)%(Filename)%(Extension)" />

		<Compile Include="..\Uno.Extensions.Reactive\**\*Attribute.cs" Link="Attributes\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
</Project>
