global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Maui.Embedding;
global using Microsoft.Maui.Platform;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Markup;
global using Uno.Extensions.Maui.Properties;
global using Application = Microsoft.UI.Xaml.Application;
global using MauiApplication = Microsoft.Maui.Controls.Application;
global using Binding = Microsoft.Maui.Controls.Binding;
global using BindingMode = Microsoft.Maui.Controls.BindingMode;
global using View = Microsoft.Maui.Controls.View;
global using MauiApp = Microsoft.Maui.Hosting.MauiApp;
global using MauiAppBuilder = Microsoft.Maui.Hosting.MauiAppBuilder;
global using IMauiContext = Microsoft.Maui.IMauiContext;
global using MauiContext = Microsoft.Maui.MauiContext;
global using NativeMauiBinding = Microsoft.Maui.Controls.Binding;
global using WinUIColor = Windows.UI.Color;
global using NativeMauiColor = Microsoft.Maui.Graphics.Color;
global using MauiResourceDictionary = Microsoft.Maui.Controls.ResourceDictionary;
global using IMauiConverter = Microsoft.Maui.Controls.IValueConverter;
global using IWinUIConverter = Microsoft.UI.Xaml.Data.IValueConverter;
global using Uno.Extensions.Maui.Models;
