name: Build Wasm
description: ""

inputs:
  package-id:  # id of input
    description: 'Compiled Package ID'
    required: true
    default: 'release_wasm'
  project-to-build:  # version of release package
    description: 'Relative path to .csproj file'
    required: true
    default: ''
  project-folder:
    description: 'csproj folder'
    required: true
    default: ''   
  artifact-retention-policy: 
    description: 'Number of days to keep the build artifacts'
    required: false
    default: '90'
  publish-artifacts: 
     description: "If true, compilation artifacts will be published and put under Job Summary section"
     required: false
     default: 'true'   

runs:
  using: "composite"
  steps:
    - name: Verify required parameters
      shell: pwsh
      run: |
            $errors = ''
            if ('' -eq '${{ inputs.project-to-build }}') { $errors = $errors + '[project-to-build] is not valid.' + "`r`n"  }
            
            if (-not ([string]::IsNullOrEmpty($errors))){
                $errors
                throw "Some required parameters are missing"
            }

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with:
        useConfigFile: true
        configFilePath: ./.github/workflows/config/gitversion.yml

    # Create the app package by building and packaging the project
    - name: Build and create package
      shell: pwsh
      run: |
        $projectFolder = '${{ inputs.project-folder }}'
        if (('' -eq $projectFolder) -and ("${{ inputs.project-to-build }}".Contains('/') )){
          Write-Host "Adjusting proj folder"
          $projectFolder = "${{ inputs.project-to-build }}".SubString(0, "${{ inputs.project-to-build }}".LastIndexOf('/'))
        }
        Write-Host "Current proj folder is: $projectFolder"

        Write-Host "Building.."
        dotnet build  -c Release -o $projectFolder\bin\Release ${{ inputs.project-to-build }}

        $finalPackageFolder = "artifacts"
        Write-Host "Creating package folder: $finalPackageFolder"
        New-Item -ItemType Directory -Force -Path $finalPackageFolder

        if ('true' -eq '${{ inputs.publish-artifacts }}') {
          Copy-Item -Path "$projectFolder\bin\Release\*" -Destination "artifacts" -recurse -Force  
        }

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ inputs.package-id }}_${{ steps.gitversion.outputs.assemblySemVer }}"
        path: artifacts
        retention-days: ${{ inputs.artifact-retention-policy }}