// <auto-generated/>
#pragma warning disable CS0618
using ErrorResponses.Client.Models;
using ErrorResponses.Client.Resources.Item.Operations;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ErrorResponses.Client.Resources.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \resources\{resourceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The operations property</summary>
        public global::ErrorResponses.Client.Resources.Item.Operations.OperationsRequestBuilder Operations
        {
            get => new global::ErrorResponses.Client.Resources.Item.Operations.OperationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources/{resourceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources/{resourceId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a resource
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ErrorResponses.Client.Models.NotFoundError">When receiving a 404 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.ConflictError">When receiving a 409 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.GeneralError">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ErrorResponses.Client.Models.NotFoundError.CreateFromDiscriminatorValue },
                { "409", global::ErrorResponses.Client.Models.ConflictError.CreateFromDiscriminatorValue },
                { "4XX", global::ErrorResponses.Client.Models.GeneralError.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a resource by ID
        /// </summary>
        /// <returns>A <see cref="global::ErrorResponses.Client.Models.Resource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ErrorResponses.Client.Models.NotFoundError">When receiving a 404 status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.GeneralError">When receiving a 4XX status code</exception>
        /// <exception cref="global::ErrorResponses.Client.Models.InternalError">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ErrorResponses.Client.Models.Resource?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ErrorResponses.Client.Models.Resource> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ErrorResponses.Client.Models.NotFoundError.CreateFromDiscriminatorValue },
                { "4XX", global::ErrorResponses.Client.Models.GeneralError.CreateFromDiscriminatorValue },
                { "5XX", global::ErrorResponses.Client.Models.InternalError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ErrorResponses.Client.Models.Resource>(requestInfo, global::ErrorResponses.Client.Models.Resource.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a resource
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get a resource by ID
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ErrorResponses.Client.Resources.Item.WithResourceItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
