global using System;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Navigation;
global using UnoConfigProject.Business.Models;
global using UnoConfigProject.Presentation;
global using UnoConfigProject.Views;
global using Uno.Extensions;
global using Uno.Extensions.Configuration;
global using Uno.Extensions.Hosting;
global using Uno.Extensions.Localization;
global using Uno.Extensions.Navigation;
global using Windows.ApplicationModel;
global using Application = Microsoft.UI.Xaml.Application;
