using TestHarness.Ext.Http.KiotaSourceGen.SourceGenClient;
using Uno.Extensions.Http.Kiota;
using Uno.Extensions.Http;

namespace TestHarness.Ext.Http.KiotaSourceGen;

/// <summary>
/// Host initialization for the Kiota Roslyn source generator
/// (AdditionalFiles with KiotaClientName metadata) test scenario.
/// <para>
/// The <c>SourceGenPetClient</c> type is generated by the Roslyn
/// incremental source generator from the <c>petstore-sourcegen.json</c>
/// OpenAPI spec declared as an <c>&lt;AdditionalFiles&gt;</c> item with
/// <c>KiotaClientName</c> metadata in the project file.
/// </para>
/// </summary>
public class KiotaSourceGenHostInit : BaseHostInitialization
{
	protected override string[] ConfigurationFiles =>
		["TestHarness.Ext.Http.KiotaSourceGen.appsettings.kiotasourcegen.json"];

	protected override IHostBuilder Custom(IHostBuilder builder) =>
		builder
			.UseHttp((context, services) =>
				services.AddKiotaClient<SourceGenPetClient>(
					context,
					options: new EndpointOptions { Url = "https://localhost:5099" })
			)
			.ConfigureServices((context, services) =>
			{
				services.AddTransient<KiotaSourceGenHomeViewModel>();
			});

	protected override void RegisterRoutes(IViewRegistry views, IRouteRegistry routes)
	{
		views.Register(
			new ViewMap<KiotaSourceGenMainPage>(),
			new ViewMap<KiotaSourceGenHomePage, KiotaSourceGenHomeViewModel>()
		);

		routes.Register(
			new RouteMap("", View: views.FindByView<KiotaSourceGenMainPage>()),
			new RouteMap("Home", View: views.FindByViewModel<KiotaSourceGenHomeViewModel>())
		);
	}
}
