<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
	<Import Project="..\tfms-non-ui.props" />

	<ItemGroup>
		<ProjectReference Include="..\Uno.Extensions.Reactive\Uno.Extensions.Reactive.csproj" />
		<ProjectReference Include="..\Uno.Extensions.Reactive.Generator\Uno.Extensions.Reactive.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
</Project>
