global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Localization;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Reflection;
global using Uno.Extensions.Navigation;
