// Marking as auto-generated to prevent StyleCop including this file
// <auto-generated />


using System.Runtime.CompilerServices;

#if !NET5_0 && !NET6_0
#pragma warning disable CS0436 

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit
    {
    }
}

#endif

