// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Inheritance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Animal : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Discriminator property for animal type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnimalType { get; set; }
#nullable restore
#else
        public string AnimalType { get; set; }
#endif
        /// <summary>The birthDate property</summary>
        public Date? BirthDate { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isAdopted property</summary>
        public bool? IsAdopted { get; set; }
        /// <summary>Name of the animal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Weight in kilograms</summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Inheritance.Client.Models.Animal"/> and sets the default values.
        /// </summary>
        public Animal()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Inheritance.Client.Models.Animal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Inheritance.Client.Models.Animal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("animalType")?.GetStringValue();
            return mappingValue switch
            {
                "bird" => new global::Inheritance.Client.Models.Bird(),
                "cat" => new global::Inheritance.Client.Models.Cat(),
                "dog" => new global::Inheritance.Client.Models.Dog(),
                _ => new global::Inheritance.Client.Models.Animal(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "animalType", n => { AnimalType = n.GetStringValue(); } },
                { "birthDate", n => { BirthDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isAdopted", n => { IsAdopted = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("animalType", AnimalType);
            writer.WriteDateValue("birthDate", BirthDate);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isAdopted", IsAdopted);
            writer.WriteStringValue("name", Name);
            writer.WriteDoubleValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
