// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Inheritance.Client.Models
{
    /// <summary>
    /// A bird
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Bird : global::Inheritance.Client.Models.Animal, IParsable
    {
        /// <summary>Whether the bird can fly</summary>
        public bool? CanFly { get; set; }
        /// <summary>Bird species</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Species { get; set; }
#nullable restore
#else
        public string Species { get; set; }
#endif
        /// <summary>Wingspan in centimeters</summary>
        public double? Wingspan { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Inheritance.Client.Models.Bird"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Inheritance.Client.Models.Bird CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Inheritance.Client.Models.Bird();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "canFly", n => { CanFly = n.GetBoolValue(); } },
                { "species", n => { Species = n.GetStringValue(); } },
                { "wingspan", n => { Wingspan = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("canFly", CanFly);
            writer.WriteStringValue("species", Species);
            writer.WriteDoubleValue("wingspan", Wingspan);
        }
    }
}
#pragma warning restore CS0618
