// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Inheritance.Client.Models
{
    /// <summary>
    /// A dog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dog : global::Inheritance.Client.Models.Animal, IParsable
    {
        /// <summary>Bark volume on a scale of 1-10</summary>
        public int? BarkVolume { get; set; }
        /// <summary>Dog breed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Breed { get; set; }
#nullable restore
#else
        public string Breed { get; set; }
#endif
        /// <summary>Whether the dog is trained</summary>
        public bool? IsTrained { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Inheritance.Client.Models.Dog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Inheritance.Client.Models.Dog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Inheritance.Client.Models.Dog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "barkVolume", n => { BarkVolume = n.GetIntValue(); } },
                { "breed", n => { Breed = n.GetStringValue(); } },
                { "isTrained", n => { IsTrained = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteIntValue("barkVolume", BarkVolume);
            writer.WriteStringValue("breed", Breed);
            writer.WriteBoolValue("isTrained", IsTrained);
        }
    }
}
#pragma warning restore CS0618
