// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Inheritance.Client.Models
{
    /// <summary>
    /// A truck
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Truck : global::Inheritance.Client.Models.Vehicle, IParsable
    {
        /// <summary>The hasFlatbed property</summary>
        public bool? HasFlatbed { get; set; }
        /// <summary>The numberOfAxles property</summary>
        public int? NumberOfAxles { get; set; }
        /// <summary>Payload capacity in kilograms</summary>
        public double? PayloadCapacity { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Inheritance.Client.Models.Truck"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Inheritance.Client.Models.Truck CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Inheritance.Client.Models.Truck();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "hasFlatbed", n => { HasFlatbed = n.GetBoolValue(); } },
                { "numberOfAxles", n => { NumberOfAxles = n.GetIntValue(); } },
                { "payloadCapacity", n => { PayloadCapacity = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("hasFlatbed", HasFlatbed);
            writer.WriteIntValue("numberOfAxles", NumberOfAxles);
            writer.WriteDoubleValue("payloadCapacity", PayloadCapacity);
        }
    }
}
#pragma warning restore CS0618
