<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
	<Import Project="..\tfms-non-ui.props" />

	<PropertyGroup>
		<Description>MVUX feed mocks for previews and UI testing</Description>
		<ImplicitUsings>false</ImplicitUsings>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Collections.Immutable" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Uno.Extensions.Reactive\Uno.Extensions.Reactive.csproj" />
	</ItemGroup>
</Project>
