



// <auto-generated>
// This file was created from a T4 template.
// Any manual changes will be overwritten.
// </auto-generated>
using System.Collections.Generic;

namespace TemplateStudioForWPF.Tests
{
    public partial class TemplateJsonValidationTests
    {
        public static IEnumerable<object[]> GetAllRelativeTemplateJsonFiles()
        {

        }
    }
}

