// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ComposedTypes.Client.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::ComposedTypes.Client.Models.ImageContent"/>, <see cref="global::ComposedTypes.Client.Models.TextContent"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContentBlock : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.ImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.ImageContent? ImageContent { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.ImageContent ImageContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? String { get; set; }
#nullable restore
#else
        public string String { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.TextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.TextContent? TextContent { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.TextContent TextContent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ComposedTypes.Client.Models.ContentBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ComposedTypes.Client.Models.ContentBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::ComposedTypes.Client.Models.ContentBlock();
            if("ImageContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ImageContent = new global::ComposedTypes.Client.Models.ImageContent();
            }
            else if("TextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TextContent = new global::ComposedTypes.Client.Models.TextContent();
            }
            else if(parseNode.GetStringValue() is string stringValue)
            {
                result.String = stringValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ImageContent != null)
            {
                return ImageContent.GetFieldDeserializers();
            }
            else if(TextContent != null)
            {
                return TextContent.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(ImageContent != null)
            {
                writer.WriteObjectValue<global::ComposedTypes.Client.Models.ImageContent>(null, ImageContent);
            }
            else if(TextContent != null)
            {
                writer.WriteObjectValue<global::ComposedTypes.Client.Models.TextContent>(null, TextContent);
            }
            else if(String != null)
            {
                writer.WriteStringValue(null, String);
            }
        }
    }
}
#pragma warning restore CS0618
