// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ComposedTypes.Client.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::ComposedTypes.Client.Models.EmailChannel"/>, <see cref="global::ComposedTypes.Client.Models.PushChannel"/>, <see cref="global::ComposedTypes.Client.Models.SmsChannel"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationChannels : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.EmailChannel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.EmailChannel? EmailChannel { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.EmailChannel EmailChannel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.PushChannel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.PushChannel? PushChannel { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.PushChannel PushChannel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.SmsChannel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.SmsChannel? SmsChannel { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.SmsChannel SmsChannel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ComposedTypes.Client.Models.NotificationChannels"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ComposedTypes.Client.Models.NotificationChannels CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var result = new global::ComposedTypes.Client.Models.NotificationChannels();
            result.EmailChannel = new global::ComposedTypes.Client.Models.EmailChannel();
            result.PushChannel = new global::ComposedTypes.Client.Models.PushChannel();
            result.SmsChannel = new global::ComposedTypes.Client.Models.SmsChannel();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(EmailChannel != null || PushChannel != null || SmsChannel != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(EmailChannel, PushChannel, SmsChannel);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ComposedTypes.Client.Models.EmailChannel>(null, EmailChannel, PushChannel, SmsChannel);
        }
    }
}
#pragma warning restore CS0618
