// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComposedTypes.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PaymentResult_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "refunded")]
        #pragma warning disable CS1591
        Refunded,
        #pragma warning restore CS1591
    }
}
