// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ComposedTypes.Client.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::ComposedTypes.Client.Models.BankTransferPayment"/>, <see cref="global::ComposedTypes.Client.Models.CreditCardPayment"/>, <see cref="global::ComposedTypes.Client.Models.DigitalWalletPayment"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentMethod : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.BankTransferPayment"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.BankTransferPayment? BankTransferPayment { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.BankTransferPayment BankTransferPayment { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.CreditCardPayment"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.CreditCardPayment? CreditCardPayment { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.CreditCardPayment CreditCardPayment { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::ComposedTypes.Client.Models.DigitalWalletPayment"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.DigitalWalletPayment? DigitalWalletPayment { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.DigitalWalletPayment DigitalWalletPayment { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ComposedTypes.Client.Models.PaymentMethod"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ComposedTypes.Client.Models.PaymentMethod CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("paymentType")?.GetStringValue();
            var result = new global::ComposedTypes.Client.Models.PaymentMethod();
            if("bank_transfer".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BankTransferPayment = new global::ComposedTypes.Client.Models.BankTransferPayment();
            }
            else if("credit_card".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreditCardPayment = new global::ComposedTypes.Client.Models.CreditCardPayment();
            }
            else if("digital_wallet".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DigitalWalletPayment = new global::ComposedTypes.Client.Models.DigitalWalletPayment();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BankTransferPayment != null)
            {
                return BankTransferPayment.GetFieldDeserializers();
            }
            else if(CreditCardPayment != null)
            {
                return CreditCardPayment.GetFieldDeserializers();
            }
            else if(DigitalWalletPayment != null)
            {
                return DigitalWalletPayment.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(BankTransferPayment != null)
            {
                writer.WriteObjectValue<global::ComposedTypes.Client.Models.BankTransferPayment>(null, BankTransferPayment);
            }
            else if(CreditCardPayment != null)
            {
                writer.WriteObjectValue<global::ComposedTypes.Client.Models.CreditCardPayment>(null, CreditCardPayment);
            }
            else if(DigitalWalletPayment != null)
            {
                writer.WriteObjectValue<global::ComposedTypes.Client.Models.DigitalWalletPayment>(null, DigitalWalletPayment);
            }
        }
    }
}
#pragma warning restore CS0618
