// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ComposedTypes.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount property</summary>
        public decimal? Amount { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>A payment method — demonstrates oneOf with object types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ComposedTypes.Client.Models.PaymentMethod? PaymentMethod { get; set; }
#nullable restore
#else
        public global::ComposedTypes.Client.Models.PaymentMethod PaymentMethod { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::ComposedTypes.Client.Models.PaymentResult_status? Status { get; set; }
        /// <summary>The transactionId property</summary>
        public Guid? TransactionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ComposedTypes.Client.Models.PaymentResult"/> and sets the default values.
        /// </summary>
        public PaymentResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ComposedTypes.Client.Models.PaymentResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ComposedTypes.Client.Models.PaymentResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ComposedTypes.Client.Models.PaymentResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDecimalValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "paymentMethod", n => { PaymentMethod = n.GetObjectValue<global::ComposedTypes.Client.Models.PaymentMethod>(global::ComposedTypes.Client.Models.PaymentMethod.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::ComposedTypes.Client.Models.PaymentResult_status>(); } },
                { "transactionId", n => { TransactionId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("amount", Amount);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<global::ComposedTypes.Client.Models.PaymentMethod>("paymentMethod", PaymentMethod);
            writer.WriteEnumValue<global::ComposedTypes.Client.Models.PaymentResult_status>("status", Status);
            writer.WriteGuidValue("transactionId", TransactionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
