// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComposedTypes.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PushChannel_platform
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ios")]
        #pragma warning disable CS1591
        Ios,
        #pragma warning restore CS1591
        [EnumMember(Value = "android")]
        #pragma warning disable CS1591
        Android,
        #pragma warning restore CS1591
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
    }
}
