// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Serialization;
namespace ComposedTypes.Client.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="bool"/>, <see cref="int"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SettingValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="bool"/></summary>
        public bool? Boolean { get; set; }
        /// <summary>Composed type representation for type <see cref="int"/></summary>
        public int? Integer { get; set; }
        /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? String { get; set; }
#nullable restore
#else
        public string String { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ComposedTypes.Client.Models.SettingValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ComposedTypes.Client.Models.SettingValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::ComposedTypes.Client.Models.SettingValue();
            if(parseNode.GetBoolValue() is bool booleanValue)
            {
                result.Boolean = booleanValue;
            }
            else if(parseNode.GetIntValue() is int integerValue)
            {
                result.Integer = integerValue;
            }
            else if(parseNode.GetStringValue() is string stringValue)
            {
                result.String = stringValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(Boolean != null)
            {
                writer.WriteBoolValue(null, Boolean);
            }
            else if(Integer != null)
            {
                writer.WriteIntValue(null, Integer);
            }
            else if(String != null)
            {
                writer.WriteStringValue(null, String);
            }
        }
    }
}
#pragma warning restore CS0618
