// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ComposedTypes.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TextContent_format
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "plain")]
        #pragma warning disable CS1591
        Plain,
        #pragma warning restore CS1591
        [EnumMember(Value = "markdown")]
        #pragma warning disable CS1591
        Markdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
    }
}
