// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ErrorResponses.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OperationRequest_operationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "activate")]
        #pragma warning disable CS1591
        Activate,
        #pragma warning restore CS1591
        [EnumMember(Value = "deactivate")]
        #pragma warning disable CS1591
        Deactivate,
        #pragma warning restore CS1591
        [EnumMember(Value = "archive")]
        #pragma warning disable CS1591
        Archive,
        #pragma warning restore CS1591
        [EnumMember(Value = "restore")]
        #pragma warning disable CS1591
        Restore,
        #pragma warning restore CS1591
        [EnumMember(Value = "clone")]
        #pragma warning disable CS1591
        Clone,
        #pragma warning restore CS1591
    }
}
