// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ErrorResponses.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Resource_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
