// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ErrorResponses.Client.Models
{
    /// <summary>
    /// Service temporarily unavailable
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceUnavailableError : ApiException, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>Scheduled maintenance window information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ErrorResponses.Client.Models.MaintenanceWindow? MaintenanceWindow { get; set; }
#nullable restore
#else
        public global::ErrorResponses.Client.Models.MaintenanceWindow MaintenanceWindow { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => MessageEscaped ?? string.Empty; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageEscaped { get; set; }
#nullable restore
#else
        public string MessageEscaped { get; set; }
#endif
        /// <summary>The retryAfterSeconds property</summary>
        public int? RetryAfterSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ErrorResponses.Client.Models.ServiceUnavailableError"/> and sets the default values.
        /// </summary>
        public ServiceUnavailableError()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ErrorResponses.Client.Models.ServiceUnavailableError"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ErrorResponses.Client.Models.ServiceUnavailableError CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ErrorResponses.Client.Models.ServiceUnavailableError();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "maintenanceWindow", n => { MaintenanceWindow = n.GetObjectValue<global::ErrorResponses.Client.Models.MaintenanceWindow>(global::ErrorResponses.Client.Models.MaintenanceWindow.CreateFromDiscriminatorValue); } },
                { "message", n => { MessageEscaped = n.GetStringValue(); } },
                { "retryAfterSeconds", n => { RetryAfterSeconds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::ErrorResponses.Client.Models.MaintenanceWindow>("maintenanceWindow", MaintenanceWindow);
            writer.WriteStringValue("message", MessageEscaped);
            writer.WriteIntValue("retryAfterSeconds", RetryAfterSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
